import type { Metadata } from "next";
import { cn } from '@/lib/utils';
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/providers/theme-provider";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Stellaria Unoffcial Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="en" suppressHydrationWarning>
        <body className={cn(
          notoSansJP.className,
          "bg-white dark:bg-[#313338]"
        )}>
          <main>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="stellaria-theme">
              {children}
            </ThemeProvider>
          </main>
        </body>
      </html>
  );
}
